name: Portfolio Updater

on:
  repository_dispatch:
    types: [update-portfolio]

jobs:

  update:

    runs-on: ubuntu-latest

    env:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt
      - name: Check Secret
        run: |
            if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
            echo "SECRET NOT FOUND"
            else
            echo "SECRET FOUND"
            fi
      
      - run: python bot.py